parameters:
- name: pythonVersion
  type: string
- name: pinRequirements
  type: boolean
  default: False
- name: envInfoArtifact
  type: string
- name: envInfoFileBase
  type: string
- name: condaEnv
  type: string
  default: interpret_conda_env

steps:
- template: conda-path-step-template.yml

- bash: brew install libomp
  displayName: Install OpenMP with Homebrew
  condition:  eq(variables['Agent.OS'], 'Darwin')

- bash: |
      python tools/generate_conda_files.py --name ${{parameters.condaEnv}} --python-version ${{parameters.pythonVersion}}
      conda env create -n ${{parameters.condaEnv}} --file=${{parameters.condaEnv}}.yaml
  displayName: 'Creating Conda Environment with dependencies'

- bash: |
      source activate ${{parameters.condaEnv}}
      python --version
  displayName: 'Verify Python version'
  
- bash: |
      source activate ${{parameters.condaEnv}}
      pip install -r requirements.txt
  displayName: 'Install pip requirements'

- template: environment-info-step-template.yml
  parameters:
    condaEnv: ${{parameters.condaEnv}}
    envInfoArtifact: ${{parameters.envInfoArtifact}}
    envInfoFileBase: ${{parameters.envInfoFileBase}}